//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectSub
    {
        public int SelectSubID { get; set; }
        public int StuID { get; set; }
        public int SubID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Sub Sub { get; set; }
    }
}
