//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub
    {
        public Sub()
        {
            this.SelectSub = new HashSet<SelectSub>();
        }
    
        public int SubID { get; set; }
        public string SubName { get; set; }
        public string SubDM { get; set; }
        public int TeacherID { get; set; }
        public string ClassTime { get; set; }
        public int NeedPeople { get; set; }
        public decimal SubPoint { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string SubJJ { get; set; }
        public int ClassPeople { get; set; }
        public int ClassAddress { get; set; }
        public string SubPictures { get; set; }
    
        public virtual ICollection<SelectSub> SelectSub { get; set; }
    }
}
